export type ProjectType = "static" | "vite" | "nextjs" | "wordpress" | "github";

export interface Project {
  slug: string;
  name: string;
  description: string;
  type: ProjectType;
  category: string;
  color: string;
  externalUrl?: string;
}

export const projects: Project[] = [
  // Static HTML Sites
  {
    slug: "wds-carpentry",
    name: "WDS Carpentry",
    description: "Carpentry & general building - Herne Bay, Kent",
    type: "static",
    category: "Client Website",
    color: "#1a1b4b",
  },
  {
    slug: "now-24-locksmiths",
    name: "Now 24 Hour Locksmiths",
    description: "Emergency locksmith website - Glasgow & Clydebank",
    type: "static",
    category: "Client Website",
    color: "#f97316",
  },
  {
    slug: "ingram-security",
    name: "Ingram Security",
    description: "Locksmith & security specialists website - Glasgow",
    type: "static",
    category: "Client Website",
    color: "#1e3a5f",
  },
  {
    slug: "arco-locksmiths",
    name: "Arco Locksmiths",
    description: "Locksmith services website",
    type: "static",
    category: "Client Website",
    color: "#3B82F6",
  },
  {
    slug: "cp-electrics",
    name: "CP Electrics",
    description: "Electrical services website",
    type: "static",
    category: "Client Website",
    color: "#F59E0B",
  },
  {
    slug: "current-tech-solutions",
    name: "Current Tech Solutions",
    description: "Tech solutions company website",
    type: "static",
    category: "Client Website",
    color: "#10B981",
  },
  {
    slug: "averis-electrical",
    name: "Averis Electrical",
    description: "Electrical contractor website",
    type: "static",
    category: "Client Website",
    color: "#8B5CF6",
  },
  {
    slug: "simon-paul-hair",
    name: "Simon Paul Hair",
    description: "Hair salon website",
    type: "static",
    category: "Client Website",
    color: "#EC4899",
  },
  {
    slug: "holmlea-locksmith",
    name: "Holmlea Locksmith",
    description: "Locksmith services website",
    type: "static",
    category: "Client Website",
    color: "#6366F1",
  },
  {
    slug: "ap-sweepz-redesign",
    name: "AP Sweepz",
    description: "Chimney sweep services redesign",
    type: "static",
    category: "Redesign",
    color: "#F97316",
  },
  {
    slug: "excel-asbestos-redesign",
    name: "Excel Asbestos",
    description: "Asbestos removal services redesign",
    type: "static",
    category: "Redesign",
    color: "#EF4444",
  },
  {
    slug: "patterniq-redesign",
    name: "PatternIQ",
    description: "PatternIQ platform redesign",
    type: "static",
    category: "Redesign",
    color: "#14B8A6",
  },
  {
    slug: "agency-portfolio",
    name: "Agency Portfolio",
    description: "Digital agency portfolio site",
    type: "static",
    category: "Portfolio",
    color: "#A855F7",
  },
  {
    slug: "ai-agency-portfolio",
    name: "AI Agency Portfolio",
    description: "AI-focused agency portfolio",
    type: "static",
    category: "Portfolio",
    color: "#06B6D4",
  },
  // TODO: Portfolio-Website needs npm install + build (heavy Three.js deps)
  // Uncomment once built and copied to public/projects/Portfolio-Website
  // {
  //   slug: "Portfolio-Website",
  //   name: "Portfolio Website",
  //   description: "Personal portfolio with React & Three.js",
  //   type: "vite",
  //   category: "Portfolio",
  //   color: "#F43F5E",
  // },
  // Next.js Projects (built to static export)
  {
    slug: "agent-dashboard",
    name: "Agent Dashboard",
    description: "AI agent monitoring dashboard",
    type: "nextjs",
    category: "App",
    color: "#2563EB",
  },
  {
    slug: "primera-redesign",
    name: "Primera Redesign",
    description: "Primera website redesign",
    type: "nextjs",
    category: "Redesign",
    color: "#DC2626",
  },
  // WordPress (external links)
  {
    slug: "mighty-theme",
    name: "Mighty Theme",
    description: "Custom WordPress theme",
    type: "wordpress",
    category: "WordPress",
    color: "#21759B",
  },
  {
    slug: "rawhoney-theme",
    name: "Raw Honey Theme",
    description: "WordPress theme for Raw Honey",
    type: "wordpress",
    category: "WordPress",
    color: "#D97706",
  },
  {
    slug: "brooks-theme-update",
    name: "Brooks Theme Update",
    description: "WordPress theme updates",
    type: "wordpress",
    category: "WordPress",
    color: "#059669",
  },
  {
    slug: "current-tech-solutions-wp",
    name: "Current Tech Solutions WP",
    description: "WordPress version of CTS site",
    type: "wordpress",
    category: "WordPress",
    color: "#7C3AED",
  },
  {
    slug: "averis-electrical-wp",
    name: "Averis Electrical WP",
    description: "WordPress version of Averis site",
    type: "wordpress",
    category: "WordPress",
    color: "#BE185D",
  },
  // GitHub Projects (deployed externally)
  {
    slug: "jcl-crm",
    name: "JCL CRM",
    description: "Digital Agency Management CRM",
    type: "github",
    category: "GitHub",
    color: "#8B5CF6",
    externalUrl: "https://crm.jclmarketing.co.uk",
  },
  {
    slug: "rraccess-crm",
    name: "RR Access CRM",
    description: "CRM for RR Access",
    type: "github",
    category: "GitHub",
    color: "#EF4444",
    externalUrl: "https://crm.rraccess.co.uk",
  },
  {
    slug: "garage-roof-crm",
    name: "Garage Roof Company CRM",
    description: "CRM for Garage Roof Company",
    type: "github",
    category: "GitHub",
    color: "#F59E0B",
    externalUrl: "https://crm.garageroofcompany.co.uk",
  },
  {
    slug: "mighty-crm",
    name: "Mighty CRM",
    description: "CRM for Mighty Structural",
    type: "github",
    category: "GitHub",
    color: "#10B981",
    externalUrl: "https://crm.mightystructural.com",
  },
  // GitHub Projects (deployed on Vercel)
  {
    slug: "jcl-project-hub",
    name: "JCL Project Hub",
    description: "This project hub dashboard",
    type: "github",
    category: "GitHub",
    color: "#171717",
    externalUrl: "https://jcl-project-hub.vercel.app",
  },
  {
    slug: "holmlea-locksmith-gh",
    name: "Holmlea Locksmith",
    description: "Modern 24/7 locksmith website for Holmlea Locksmith Services, Glasgow",
    type: "github",
    category: "GitHub",
    color: "#6366F1",
    externalUrl: "https://holmlea-locksmith.vercel.app",
  },
  {
    slug: "acro-locksmith-gh",
    name: "Arco Locksmiths",
    description: "24/7 Emergency Locksmith serving Ayrshire, Glasgow & beyond",
    type: "github",
    category: "GitHub",
    color: "#3B82F6",
    externalUrl: "https://acro-locksmith.vercel.app",
  },
  {
    slug: "cp-electrical-gh",
    name: "CP Electrical",
    description: "Electrical services website deployed on Vercel",
    type: "github",
    category: "GitHub",
    color: "#F59E0B",
    externalUrl: "https://cp-electrical.vercel.app",
  },
];

export const categories = [...new Set(projects.map((p) => p.category))];
